[workspace]
authors = ["Mingxuan Che <mxche2019@outlook.com>"]
channels = ["conda-forge"]
name = "BO_ResNet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
torch = ">=2.7.1, <3"
torchvision = ">=0.22.1, <0.23"
gpytorch = ">=1.14, <2"
numpy = ">=2.2.6, <3"
matplotlib = ">=3.10.3, <4"
pre-commit = ">=4.2.0, <5"
seaborn = ">=0.13.2, <0.14"
scipy = ">=1.15.3, <2"
tqdm = ">=4.67.1, <5"
pillow = ">=10.0.0, <11"
